/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kancv1' at '8/19/18 1:54 AM' with Gradle 2.14.1
 *
 * @author kancv1, @date 8/19/18 1:54 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
